<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
	name="jaxb.gen.only"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns="urn:jaxb.gen.only" 
	targetNamespace="urn:jaxb.gen.only">

	<wsdl:types>
		<xsd:schema>
			<xsd:import schemaLocation="./gettimetypes/getTimeTypesResponse.xsd" namespace="urn:ProfdocHISMessage:GetTimeTypes:Response"/>
			<xsd:import schemaLocation="./gettimetypes/getTimeTypesRequest.xsd" namespace="urn:ProfdocHISMessage:GetTimeTypes:Request"/>
			<xsd:import schemaLocation="./error/error.xsd" namespace="urn:ProfdocHISMessage:Error"/>
		</xsd:schema>
	</wsdl:types>

</wsdl:definitions>
