<?xml version="1.0" encoding="utf-8"?>
<!-- 
 Licensed to the Apache Software Foundation (ASF) under one
 or more contributor license agreements. See the NOTICE file
 distributed with this work for additional information
 regarding copyright ownership. The ASF licenses this file
 to you under the Apache License, Version 2.0 (the
 "License"); you may not use this file except in compliance
 with the License. You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied. See the License for the
 specific language governing permissions and limitations
 under the License.
 -->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:tjs="urn:riv:crm:scheduling:GetAllTimeTypesResponder:1" xmlns:tns="urn:riv:crm:scheduling:GetAllTimeTypes:1:rivtabp20" name="GetAllTimeTypesInteraction" targetNamespace="urn:riv:crm:scheduling:GetAllTimeTypes:1:rivtabp20">
	<xs:annotation>
		<xs:documentation>
		Tjänsteinteraktionens namn: GetAvailableDatesInteraction
		Beskrivning: 
			Interaction to retrieve all time types supported by a healthcare facility.
		Revisioner: 
			2009-10-26: Utkast Version 1.0, johan.eltes@callistaenterprise.se
			2010-04-21: Fastställd version 1.0, johan.eltes@callistaenterprise.se		
		Tjänstedomän: crm:scheduling
		Tjänsteinteraktionstyp: Fråga-svar
		RIV Teknisk Anvisning: Basic Profile 2.0
		Förvaltas av: Örebro Läns Landsting
	</xs:documentation>
	</xs:annotation>
	<wsdl:types>
		<xs:schema>
			<xs:import schemaLocation="GetAllTimeTypesResponder_1.0.xsd" namespace="urn:riv:crm:scheduling:GetAllTimeTypesResponder:1"/>
		</xs:schema>
		<xs:schema>
			<xs:import schemaLocation="../../core_components/ws-addressing-1.0.xsd" namespace="http://www.w3.org/2005/08/addressing"/>
		</xs:schema>
	</wsdl:types>
	<wsdl:message name="GetAllTimeTypesRequest">
		<xs:annotation>
			<xs:documentation>
			LogicalAddress is the hsaid of the healthcare_facility that is requested to present its supported time types
		</xs:documentation>
		</xs:annotation>
		<wsdl:part name="LogicalAddress" element="wsa:To"/>
		<wsdl:part name="parameters" element="tjs:GetAllTimeTypes"/>
	</wsdl:message>
	<wsdl:message name="GetAllTimeTypesResponse">
		<wsdl:part name="parameters" element="tjs:GetAllTimeTypesResponse"/>
	</wsdl:message>
	<wsdl:portType name="GetAllTimeTypesResponderInterface">
		<wsdl:operation name="GetAllTimeTypes">
			<wsdl:input message="tns:GetAllTimeTypesRequest"/>
			<wsdl:output message="tns:GetAllTimeTypesResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="GetAllTimeTypesResponderBinding" type="tns:GetAllTimeTypesResponderInterface">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="GetAllTimeTypes">
			<soap:operation soapAction="urn:riv:crm:scheduling:GetAllTimeTypesResponder:1:GetAllTimeTypes"/>
			<wsdl:input>
				<soap:header use="literal" message="tns:GetAllTimeTypesRequest" part="LogicalAddress"/>
				<soap:body use="literal" parts="parameters"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="GetAllTimeTypesResponderService">
		<wsdl:port name="GetAllTimeTypesResponderPort" binding="tns:GetAllTimeTypesResponderBinding">
			<soap:address location="https://webbokatest.orebroll.sjunet.org/BookingService/GetAllTimeTypesInteractionWSI.asmx"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
