<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/MapRivToProfDocHisMessage_UpdateBooking_req.map" md5sum="ff8bb26b3d910710e5df90aacf739fa0" version="7.0.400" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.400
*
*   Mapping file:		MapRivToProfDocHisMessage_UpdateBooking_req.map
*   Map declaration(s):	MapRivToProfDocHisMessage_UpdateBooking_req
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Burn%253Amvk%253Aasb%253Atidbok%253Ainteraction%253AUpdateBooking%253A1%253A0%257DUpdateBookingRequest/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Burn%253Amvk%253Aasb%253Atakecare%253Av100%253AupdateBookingInternalInterface%257DinvokeTakeCareRequestMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:in="urn:mvk:asb:tidbok:1:0"
    xmlns:in2="urn:mvk:asb:common:base:1"
    xmlns:in4="urn:mvk:asb:tidbok:UpdateBookingResponder:1:0"
    xmlns:in3="wsdl.urn:mvk:asb:tidbok:interaction:UpdateBooking:1:0"
    xmlns:out="urn:mvk:asb:takecare:v100:TakeCareCommonAttribute"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:out2="urn:mvk:asb:takecare:v100:updateBookingInternalInterface"
    xmlns:out3="urn:ProfdocHISMessage:RescheduleBooking:Request"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:xsd4xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:out4="wsdl.urn:mvk:asb:takecare:v100:updateBookingInternalInterface"
    xmlns:TimebookUtils="xalan://se.modul1.mvk.asb.timebooking.takecare.java.TimebookUtils"
    xmlns:XmlHandler="xalan://se.modul1.mvk.asb.timebooking.takecare.java.XmlHandler"
    xmlns:map="http://Mvk_Scheduling_TakeCare_Adapter/xslt/MapRivToProfDocHisMessage_UpdateBooking_req"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="set in msl math exsl in2 in3 date in4 xalan str XmlHandler TimebookUtils map"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <dataObject>
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'out4:invokeTakeCareRequestMsg'"/>
            </xsl:attribute>
            <xsl:call-template name="map:MapRivToProfDocHisMessage_UpdateBooking_req2">
              <xsl:with-param name="body" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </dataObject>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="body" mode="map:MapRivToProfDocHisMessage_UpdateBooking_req"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:MapRivToProfDocHisMessage_UpdateBooking_req">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out4:invokeTakeCareRequestMsg'"/>
      </xsl:attribute>
      <out2:invokeTakeCare>
        <out3:ProfdocHISMessage>
          <!-- a simple mapping with no associated source:  to "InvokingSystem"(string) -->
          <xsl:attribute name="InvokingSystem">
            <xsl:value-of select="'InvSysMVK'"/>
          </xsl:attribute>
          <!-- a simple mapping with no associated source:  to "MsgType"(string) -->
          <xsl:attribute name="MsgType">
            <xsl:value-of select="'Request'"/>
          </xsl:attribute>
          <!-- a simple mapping with no associated source:  to "Time"(unsignedLong) -->
          <xsl:attribute name="Time">
            <xsl:value-of select="TimebookUtils:getTodayDatesAsYYYYMMDDHHMMSS()"/>
          </xsl:attribute>
          <!-- a simple data mapping: "in4:UpdateBooking/in4:requestedTimeslot/in:bookingId"(BookingIdType) to "BookingId"(string) -->
          <BookingId>
            <xsl:value-of select="in4:UpdateBooking/in4:requestedTimeslot/in:bookingId"/>
          </BookingId>
          <!-- a simple mapping with no associated source:  to "CareUnitIdType"(string) -->
          <CareUnitIdType>
            <xsl:text>HSAID</xsl:text>
          </CareUnitIdType>
          <!-- a simple data mapping: "in4:UpdateBooking/in4:requestedTimeslot/in:healthcare_facility"(HsaIdType) to "CareUnitId"(string) -->
          <CareUnitId>
            <xsl:value-of select="in4:UpdateBooking/in4:requestedTimeslot/in:healthcare_facility"/>
          </CareUnitId>
          <!-- a simple data mapping: "in4:UpdateBooking/in4:requestedTimeslot/in:startTimeInclusive"(TS) to "StartTime"(unsignedLong) -->
          <StartTime>
            <!-- variables for custom code -->
            <xsl:variable name="startTimeInclusive" select="in4:UpdateBooking/in4:requestedTimeslot/in:startTimeInclusive"/>
            <xsl:value-of select="TimebookUtils:removeSecondsFromDateTime($startTimeInclusive)"/>
          </StartTime>
          <!-- a simple data mapping: "in4:UpdateBooking/in4:requestedTimeslot/in:endTimeExclusive"(TS) to "EndTime"(unsignedLong) -->
          <EndTime>
            <!-- variables for custom code -->
            <xsl:variable name="endTimeExclusive" select="in4:UpdateBooking/in4:requestedTimeslot/in:endTimeExclusive"/>
            <xsl:value-of select="TimebookUtils:removeSecondsFromDateTime($endTimeExclusive)"/>
          </EndTime>
          <!-- a simple data mapping: "in4:UpdateBooking/in4:requestedTimeslot/in:timeTypeID"(TimeTypeIDType) to "TimeTypeId"(unsignedShort) -->
          <TimeTypeId>
            <!-- variables for custom code -->
            <xsl:variable name="timeTypeID" select="in4:UpdateBooking/in4:requestedTimeslot/in:timeTypeID"/>
            <xsl:value-of select="TimebookUtils:convertStringValueToInt($timeTypeID)"/>
          </TimeTypeId>
          <!-- a simple data mapping: "in4:UpdateBooking/in4:requestedTimeslot/in:resourceID"(ResourceIDType) to "ResourceId"(unsignedLong) -->
          <ResourceId>
            <!-- variables for custom code -->
            <xsl:variable name="resourceID" select="in4:UpdateBooking/in4:requestedTimeslot/in:resourceID"/>
            <xsl:value-of select="TimebookUtils:convertStringValueToLong($resourceID)"/>
          </ResourceId>
          <!-- a simple data mapping: "in4:UpdateBooking/in4:requestedTimeslot/in:reason"(string) to "PatientReason"(string) -->
          <xsl:if test="in4:UpdateBooking/in4:requestedTimeslot/in:reason">
            <PatientReason>
              <xsl:value-of select="in4:UpdateBooking/in4:requestedTimeslot/in:reason"/>
            </PatientReason>
          </xsl:if>
        </out3:ProfdocHISMessage>
        <!-- a simple data mapping: "in4:UpdateBooking/in4:mvkAdressering/in:configData/serviceComponent/endpointAddress"(EndpointAddressType) to "TargetAdressURLString"(string) -->
        <TargetAdressURLString>
          <xsl:value-of select="in4:UpdateBooking/in4:mvkAdressering/in:configData/serviceComponent/endpointAddress"/>
        </TargetAdressURLString>
        <ProfdocHISMessageHeader>
          <!-- a simple mapping with no associated source:  to "TCUser"(string) -->
          <TCUser>
            <xsl:text></xsl:text>
          </TCUser>
          <!-- a simple mapping with no associated source:  to "TCPassword"(string) -->
          <TCPassword>
            <xsl:text></xsl:text>
          </TCPassword>
          <!-- a simple mapping with no associated source:  to "externalUser"(string) -->
          <externalUser>
            <xsl:text>ExtUsrMVK</xsl:text>
          </externalUser>
          <!-- a simple mapping with no associated source:  to "careUnitIdType"(string) -->
          <careUnitIdType>
            <xsl:text>HSAID</xsl:text>
          </careUnitIdType>
          <!-- a simple data mapping: "in4:UpdateBooking/in4:mvkAdressering/in:configData/logicalAdressat/logicalAddress"(LogicalAddressType) to "hsaId"(string) -->
          <xsl:if test="in4:UpdateBooking/in4:mvkAdressering/in:configData/logicalAdressat/logicalAddress">
            <hsaId>
              <xsl:value-of select="in4:UpdateBooking/in4:mvkAdressering/in:configData/logicalAdressat/logicalAddress"/>
            </hsaId>
          </xsl:if>
          <!-- a simple mapping with no associated source:  to "invokingSystem"(string) -->
          <invokingSystem>
            <xsl:text>InvSysMVK</xsl:text>
          </invokingSystem>
        </ProfdocHISMessageHeader>
      </out2:invokeTakeCare>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:MapRivToProfDocHisMessage_UpdateBooking_req2">
    <xsl:param name="body"/>
    <out2:invokeTakeCare>
      <out3:ProfdocHISMessage>
        <!-- a simple mapping with no associated source:  to "InvokingSystem"(string) -->
        <xsl:attribute name="InvokingSystem">
          <xsl:value-of select="'InvSysMVK'"/>
        </xsl:attribute>
        <!-- a simple mapping with no associated source:  to "MsgType"(string) -->
        <xsl:attribute name="MsgType">
          <xsl:value-of select="'Request'"/>
        </xsl:attribute>
        <!-- a simple mapping with no associated source:  to "Time"(unsignedLong) -->
        <xsl:attribute name="Time">
          <xsl:value-of select="TimebookUtils:getTodayDatesAsYYYYMMDDHHMMSS()"/>
        </xsl:attribute>
        <!-- a simple data mapping: "$body/in4:UpdateBooking/in4:requestedTimeslot/in:bookingId"(BookingIdType) to "BookingId"(string) -->
        <BookingId>
          <xsl:value-of select="$body/in4:UpdateBooking/in4:requestedTimeslot/in:bookingId"/>
        </BookingId>
        <!-- a simple mapping with no associated source:  to "CareUnitIdType"(string) -->
        <CareUnitIdType>
          <xsl:text>HSAID</xsl:text>
        </CareUnitIdType>
        <!-- a simple data mapping: "$body/in4:UpdateBooking/in4:requestedTimeslot/in:healthcare_facility"(HsaIdType) to "CareUnitId"(string) -->
        <CareUnitId>
          <xsl:value-of select="$body/in4:UpdateBooking/in4:requestedTimeslot/in:healthcare_facility"/>
        </CareUnitId>
        <!-- a simple data mapping: "$body/in4:UpdateBooking/in4:requestedTimeslot/in:startTimeInclusive"(TS) to "StartTime"(unsignedLong) -->
        <StartTime>
          <!-- variables for custom code -->
          <xsl:variable name="startTimeInclusive" select="$body/in4:UpdateBooking/in4:requestedTimeslot/in:startTimeInclusive"/>
          <xsl:value-of select="TimebookUtils:removeSecondsFromDateTime($startTimeInclusive)"/>
        </StartTime>
        <!-- a simple data mapping: "$body/in4:UpdateBooking/in4:requestedTimeslot/in:endTimeExclusive"(TS) to "EndTime"(unsignedLong) -->
        <EndTime>
          <!-- variables for custom code -->
          <xsl:variable name="endTimeExclusive" select="$body/in4:UpdateBooking/in4:requestedTimeslot/in:endTimeExclusive"/>
          <xsl:value-of select="TimebookUtils:removeSecondsFromDateTime($endTimeExclusive)"/>
        </EndTime>
        <!-- a simple data mapping: "$body/in4:UpdateBooking/in4:requestedTimeslot/in:timeTypeID"(TimeTypeIDType) to "TimeTypeId"(unsignedShort) -->
        <TimeTypeId>
          <!-- variables for custom code -->
          <xsl:variable name="timeTypeID" select="$body/in4:UpdateBooking/in4:requestedTimeslot/in:timeTypeID"/>
          <xsl:value-of select="TimebookUtils:convertStringValueToInt($timeTypeID)"/>
        </TimeTypeId>
        <!-- a simple data mapping: "$body/in4:UpdateBooking/in4:requestedTimeslot/in:resourceID"(ResourceIDType) to "ResourceId"(unsignedLong) -->
        <ResourceId>
          <!-- variables for custom code -->
          <xsl:variable name="resourceID" select="$body/in4:UpdateBooking/in4:requestedTimeslot/in:resourceID"/>
          <xsl:value-of select="TimebookUtils:convertStringValueToLong($resourceID)"/>
        </ResourceId>
        <!-- a simple data mapping: "$body/in4:UpdateBooking/in4:requestedTimeslot/in:reason"(string) to "PatientReason"(string) -->
        <xsl:if test="$body/in4:UpdateBooking/in4:requestedTimeslot/in:reason">
          <PatientReason>
            <xsl:value-of select="$body/in4:UpdateBooking/in4:requestedTimeslot/in:reason"/>
          </PatientReason>
        </xsl:if>
      </out3:ProfdocHISMessage>
      <!-- a simple data mapping: "$body/in4:UpdateBooking/in4:mvkAdressering/in:configData/serviceComponent/endpointAddress"(EndpointAddressType) to "TargetAdressURLString"(string) -->
      <TargetAdressURLString>
        <xsl:value-of select="$body/in4:UpdateBooking/in4:mvkAdressering/in:configData/serviceComponent/endpointAddress"/>
      </TargetAdressURLString>
      <ProfdocHISMessageHeader>
        <!-- a simple mapping with no associated source:  to "TCUser"(string) -->
        <TCUser>
          <xsl:text></xsl:text>
        </TCUser>
        <!-- a simple mapping with no associated source:  to "TCPassword"(string) -->
        <TCPassword>
          <xsl:text></xsl:text>
        </TCPassword>
        <!-- a simple mapping with no associated source:  to "externalUser"(string) -->
        <externalUser>
          <xsl:text>ExtUsrMVK</xsl:text>
        </externalUser>
        <!-- a simple mapping with no associated source:  to "careUnitIdType"(string) -->
        <careUnitIdType>
          <xsl:text>HSAID</xsl:text>
        </careUnitIdType>
        <!-- a simple data mapping: "$body/in4:UpdateBooking/in4:mvkAdressering/in:configData/logicalAdressat/logicalAddress"(LogicalAddressType) to "hsaId"(string) -->
        <xsl:if test="$body/in4:UpdateBooking/in4:mvkAdressering/in:configData/logicalAdressat/logicalAddress">
          <hsaId>
            <xsl:value-of select="$body/in4:UpdateBooking/in4:mvkAdressering/in:configData/logicalAdressat/logicalAddress"/>
          </hsaId>
        </xsl:if>
        <!-- a simple mapping with no associated source:  to "invokingSystem"(string) -->
        <invokingSystem>
          <xsl:text>InvSysMVK</xsl:text>
        </invokingSystem>
      </ProfdocHISMessageHeader>
    </out2:invokeTakeCare>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
